#define OS_DETECTION_KEYBOARD_RESET
#define OS_DETECTION_SINGLE_REPORT

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define LEADER_TIMEOUT 333
#define LEADER_PER_KEY_TIMEOUT
#define LEADER_NO_TIMEOUT
//#define LEADER_KEY_STRICT_KEY_PROCESSING
